# Generated by Django 4.2.1 on 2023-05-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['updated', 'created']},
        ),
    ]
